import type { UiContract } from './types'

export const defaultContract: UiContract = {
  schemaVersion: '0.3.0', meta: { name: 'Business UI Contract', description: 'Button policy prototype for the UI Contract Editor.' }, product: { systemType: 'business-admin', informationDensity: 'compact', visualTone: 'calm' },
  designPolicy: { colorProfileId: 'default', brandIdentity: { mark: '#2563eb', markBackground: '#ffffff', markBorder: '#cbd5e1' }, color: { light: { brandBackground: '#eff6ff', brandText: '#172554', primary: '#2563eb', primaryText: '#ffffff', success: '#15803d', warning: '#b45309', danger: '#b91c1c', info: '#0f766e', focusOuter: '#111827', focusInner: '#facc15', background: '#f1f5f9', surface: '#ffffff', surfaceSoft: '#f8fafc', border: '#cbd5e1', text: '#0f172a', mutedText: '#64748b' }, dark: { brandBackground: '#020617', brandText: '#f8fafc', primary: '#60a5fa', primaryText: '#0f172a', success: '#4ade80', warning: '#fbbf24', danger: '#f87171', info: '#2dd4bf', focusOuter: '#facc15', focusInner: '#111827', background: '#0f172a', surface: '#111827', surfaceSoft: '#1f2937', border: '#334155', text: '#f8fafc', mutedText: '#cbd5e1' } } },
  interactionPolicy: { focus: { visibility: 'keyboard-and-active-inputs', indicatorStyle: 'outer-ring' }, validation: { trigger: 'submit-or-step', presentation: 'field-and-summary' }, availability: { treatment: 'keep-enabled-explain-on-action', layout: 'preserve-space-for-temporary-state' }, confirmation: { surface: 'danger-dialog', scope: 'destructive-only' }, loading: { feedback: 'communicate-busy-state' }, stateFeedback: { guidance: 'explain-condition-and-next-step' } },
  componentPolicy: { button: { primaryEmphasis: 'filled', secondaryEmphasis: 'outline', dangerPlacement: 'separated', dangerEmphasis: 'outline', iconAdornment: 'text-only-default', iconOnlyPolicy: 'avoid-icon-only' }, textField: { fieldStyle: 'outlined', labelPlacement: 'top', requiredIndicator: 'mark-optional', messageAreaBehavior: 'reserved-message-area', placeholderUsage: 'avoid-placeholder' }, select: { emptyDisplay: 'placeholder-text', multiSelectedItemDisplay: 'chips', multiRemoveAffordance: 'chip-remove-button', searchFieldTreatment: 'embedded-search-field' }, tabs: { treatment: 'segmented-contained', adornment: 'text-only' }, toggle: { treatment: 'switch-control', labelPolicy: 'visible-label' }, checkbox: { groupLayout: 'stacked-list', choiceSurface: 'plain-label', mixedState: 'show-indeterminate' }, card: { treatment: 'outlined-card', interaction: 'static-card' }, sidePanel: { relationship: 'persistent-inspector', responsive: 'collapse-to-toggle' } },
  screenPatternPolicy: { searchList: 'standard-search-list', formSection: 'grouped-form-section' },
}
